Type: "AWS::Route53::RecordSetGroup"
Properties:
  HostedZoneName: "${self:custom.rootDomain}."
  Comment: "DNS records associated with danielhollcraft static site"
  RecordSets:
    - Name: "${self:custom.rootDomain}"
      Type: A
      AliasTarget:
        DNSName: {"Fn::GetAtt": CDN.DomainName}
        # magic cloudfront hosted zone id
        # see http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget.html
        HostedZoneId: Z2FDTNDATAQYW2
    - Name: "www.${self:custom.rootDomain}"
      Type: A
      AliasTarget:
        DNSName: {"Fn::GetAtt": CDN.DomainName}
        HostedZoneId: Z2FDTNDATAQYW2
    - Name: "${self:custom.rootDomain}"
      # This AAAA record only works for some CloudFront
      # distributions because IPv6 support isn't rolled out entirely
      Type: AAAA
      AliasTarget:
        DNSName: {"Fn::GetAtt": CDN.DomainName}
        HostedZoneId: Z2FDTNDATAQYW2
    - Name: "www.${self:custom.rootDomain}"
      # This AAAA record only works for some CloudFront
      # distributions because IPv6 support isn't rolled out entirely
      Type: AAAA
      AliasTarget:
        DNSName: {"Fn::GetAtt": CDN.DomainName}
        HostedZoneId: Z2FDTNDATAQYW2
