service: danielhollcraft

frameworkVersion: ">=1.9.0 <2.0.0"

custom:
  stage: ${opt:stage, self:provider.stage}
  rootDomain: danielhollcraft.com
  devDomains:
    - dev.danielhollcraft.com
  prodDomains:
    - www.danielhollcraft.com
    - danielhollcraft.com

provider:
  name: aws
  region: us-east-1

resources:
  Mappings: ${file(deploy/resources/mappings.yml)}
  Outputs: ${file(deploy/resources/outputs.yml)}
  Resources:
    WebSite:
      Type: "AWS::S3::Bucket"
      Properties:
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: 404/index.html
    DnsRecords: ${file(deploy/resources/${self:custom.stage}-dns.yml)}
    SSLCert: ${file(deploy/resources/${self:custom.stage}-ssl.yml)}
    CDN:
      Type: "AWS::CloudFront::Distribution"
      Properties:
        DistributionConfig:
          ViewerCertificate:
            AcmCertificateArn: {Ref: SSLCert}
            SslSupportMethod: sni-only
          Enabled: true
          HttpVersion: http2
          Aliases: ${self:custom.${self:custom.stage}Domains}
          DefaultRootObject: index.html
          Origins:
            - DomainName: {"Fn::Join": ["", [{Ref: WebSite}, ".", {"Fn::FindInMap": [RegionMap, {Ref: "AWS::Region"}, websiteendpoint]}]]}
              Id: S3Origin
              CustomOriginConfig:
                HTTPPort: 80
                HTTPSPort: 443
                OriginProtocolPolicy: http-only
          DefaultCacheBehavior:
            ViewerProtocolPolicy: redirect-to-https
            TargetOriginId: S3Origin
            AllowedMethods:
              - GET
              - HEAD
            Compress: true
            DefaultTTL: 30
            MinTTL: 10
            ForwardedValues:
              QueryString: true
